config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :posts 
  resources :bookmark,only: [:index,:create,:destroy]
  resources :profile, only: [:show] 
  resources :friendships  do
    post 'fb_friends', :on => :collection
  end
  resources :users do
    get 'search', on: :collection
  end
  match "/facebook_profile" => "facebook#facebook_profile",via: [:get, :post]
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
  belongs_to :friend, :class_name => "User",:foreign_key => 'friend_id'

  enum status: {"pending": "pending", "accepted": "accepted", "rejected": "rejected"}
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:update,:destroy]
  
  def index
    @users = User.all
  end

  #Send a friendship request(add friend)
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = t('friendship.create')
    else
      flash[:notice] = t('friendship.create_error')
    end
    redirect_to friendships_path
  end

  # Only For friendship request (accept/reject)
  def update
    if params[:status] == 'accept'
      @friendship.accepted!      
      flash[:notice] = t('friendship.accept')
    elsif params[:status] == 'ignore'
      @friendship.rejected!
      flash[:notice] = t('friendship.ignore')
    end
    redirect_to friendships_path
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] =  t('friendship.remove')
    redirect_to friendships_path
  end

  private

  def set_friendship
    @friendship = Friendship.find_by_id(params[:id])
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/index.html.erb
<div class="col-md-12">
	<div class="col-md-5"><h3>Facebook Friends</h3>
	<% if current_user.oauth_token.present? %>
		<%= link_to 'Invite fb friends',facebook_profile_path, :method => :get, :id => "invite_fb_friends", :class => "btn btn-primary btn-sm space" %>
		<% else %>
		<%= link_to "Sign up by facebook",user_facebook_omniauth_authorize_path,:method => :get, :class => "btn btn-primary btn-sm space" %>
		<% end %>
	</div>

	<div class="col-md-4">				 
		<h3>Your Friends</h3>
		<% if current_user.all_friends.each do |friend| %>
			<% friendship = current_user.get_mutual_friendship_with(friend) %>
			<% friendship = current_user.get_mutual_friendship_with(friend) %>
				<% if friendship.accepted? %>
					<table>
						<tr>
							<td><%=h friend.email %></td>
							<td><%= link_to "Unfriend", friendship_path(friendship), :method => :delete,:class => "btn btn-primary btn-sm space" %></td>
						</tr>
					</table>
				<% end %>
		<% end %>
		<% end %>
		<%= link_to 'View Requests', friendship_path(current_user) %>
	</div>
	
	<div class="col-md-3">
		<h3>Search Friends by email</h3>
		<%= form_tag search_users_path, :method => "get" do %>
			<%= text_field_tag :search, params[:search], data: {autocomplete_source: User.order(:email).map(&:email)} %>
			<%= submit_tag "Search" %>
		<% end %>
	</div>
</div>

app/views/friendships/show.html.erb
<h2>Sent Friend Requests</h2>
<table>
  <% current_user.friendships.pending.each do |friendship| %>
    <tr>
      <% if friendship.friend.present? %>
        <td><%=h friendship.friend.email %></td>
        <td><%= link_to "Cancel sent Request", friendship, :method => :delete, :class => "btn btn-primary btn-sm space" %></td>
      <% else %>
        <td><b>Deleted user</b></td>
        <td><%= link_to "Cancel sent Request space", "#", :class => "btn btn-primary btn-sm" %>
          <% flash[:notice] = "User Not available" %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<h2>View Friend requests</h2>
<table>
  <% current_user.inverse_friendships.pending.each do |friendship| %>
    <tr>
      <% if friendship.user.present? %>
        <td><%=h friendship.user.email %></td>
        <td>
          <%= link_to "Accept", friendship_path(friendship, status: 'accept'), method:"put", :class => "btn btn-primary btn-sm space" %>
          <%= link_to "Ignore", friendship_path(friendship, status: 'ignore'), method:"put", :class => "btn btn-primary btn-sm space" %>
        </td>
      <% else %>
        <td><b>Deleted user</b></td>
      <% end %>
    </tr>
  <% end %>
</table>