config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :posts 
  resources :bookmark,only: [:index,:create,:destroy]
  resources :profile, only: [:show] 
  resources :friendships  do
    post 'fb_friends', :on => :collection
  end
  resources :users do
    get 'search', on: :collection
  end
  match "/facebook_profile" => "facebook#facebook_profile",via: [:get, :post]
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
	belongs_to :user
  belongs_to :post
  validates :user_id, presence: { message: "must be given" }
  validates :post_id, presence: { message: "should be select to bookmarked" }
  self.per_page = 20
end

app/controllers/bookmark_controller.rb
class BookmarkController < ApplicationController

  def index
    @bookmarks = current_user.bookmarked_posts.paginate(:page => params[:page], :per_page => 20).order('created_at DESC')
  end

  def create
    post = Post.find(params[:post_id])
    bookmark = post.bookmarks.build(:user_id => current_user.id)
    if bookmark.save
      flash[:notice] = t('bookmark.save')
    else
      # bookmark.errors.full_messages
      # flash[:error] = t('bookmark.not_save')
      flash[:error] = bookmark.errors.full_messages
    end
    redirect_to posts_path
  end

  def destroy
    bookmark = Bookmark.where(params[:id]).first
    bookmark.destroy if bookmark.present?
    flash[:notice] = t('bookmark.remove')
    redirect_to posts_path
  end
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/views/bookmark/index.html.erb
<% if @bookmarks.count == 0 %>
  <h3>No Posts Saved yet</h3>
<% else %>
  <h3>Bookmarked posts</h3>
  <ul>
    <%= @bookmarks.each do |post|%>
      <li>
        <div id="my-posts">
          <p><%= post.content %></p>
          <p class="img"><%= image_tag post.image %></p>
          <p>
            Privacy: <%= post.privacy_type %>
            <small><em><%= post.timestamp %></em></small>
          </p>
          <p>
            <% if current_user.id == post.user_id%>
              <%= link_to 'Destroy', post_path(post),
              data: {:confirm => 'Are you sure?'}, :method => :delete %>
              <%= link_to 'Edit',edit_post_path(post), remote:true%>
            <% end %>
          </p>
          <p>
            <% bookmarked_post = current_user.bookmarks.find_by(post_id: post.id) %>
            <% if bookmarked_post.present? %>
              <%= link_to "remove", bookmark_path(bookmarked_post.id), :method => :delete %>
            <% else %>
              <%= link_to "save", bookmark_index_path(:post_id => post.id), :method => :post %>
            <% end %>
        </p>
        </div>
      </li>
    <% end %>
  </ul>
<%= will_paginate @bookmarks %>
<% end %>