config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :posts 
  resources :bookmark,only: [:index,:create,:destroy]
  resources :profile, only: [:show] 
  resources :friendships  do
    post 'fb_friends', :on => :collection
  end
  resources :users do
    get 'search', on: :collection
  end
  match "/facebook_profile" => "facebook#facebook_profile",via: [:get, :post]
end

app/models/post.rb
class Post < ApplicationRecord 
  belongs_to :user
  delegate :test_user, :test_user2, to: :user
  delegate :sum, to: :CONSTANT_ARRAY
  has_many :pictures, as: :imageable
  has_many :bookmarks, dependent: :destroy
  validate :content_or_image	
  enum privacy_type: {"All": "public", "friends": "friends", "me": "me"}
  mount_uploader :image, ImageUploader
  self.per_page = 10

  scope :user_all_friends_post, lambda { |user| 
    where(:user_id => user.all_friends) }
  scope :friends_posts, -> { where(posts: {privacy_type: "friends" }) }
  scope :all_posts, -> { where(posts: {privacy_type: "public" }) }

  def content_or_image
    unless !content.blank? or !image.blank? 
      errors.add(:base, "Specify a content or a image, not both")
    end
  end

  def timestamp
    created_at.try(:strftime,'%d %B %Y %H:%M:%S')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  respond_to :html, :js, :json

  def new
    @post = Post.new
  end

  def index
    # f_posts = Post.user_all_friends_post(current_user) 
    # all_posts = f_posts.friends_posts + current_user.posts + Post.all.all_posts
    # @posts = all_posts.sort_by(&:updated_at).paginate(page: params[:page],per_page: 3)
    # respond_to do |format|
    #   format.html
    #   format.js
    # end
    @posts = Post.paginate(page: params[:page], per_page: 15).order('created_at ASC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = t('post.create')
    else
      flash[:notice] =  t('post.create_error')
    end
    redirection_path
  end

  def destroy
    @post.destroy
    redirection_path
  end

  def update
    @post.update_attributes(post_params)
    redirection_path
  end

  private
    def redirection_path
      redirect_to posts_path
    end

    def post_params
      params.require(:post).permit(:content, :image,:privacy_type)
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, remote: true do |post_form| %>
  <div class="col-md-12 text-left">
    <div class="col-md-6">
      <%= post_form.label :content %><br>
      <%= post_form.text_field :content, class: 'test', value: '' %>
    </div>
        
    <div class="col-md-6">
      <%= post_form.label :image %><br>
      <%= post_form.file_field :image %>
    </div>
       
    <div class="col-md-12 post-content">
      <%= post_form.label :privacy_type%> 
      <%= post_form.select :privacy_type, Post.privacy_types %>
    </div>
       
    <div class="col-md-12 post-content">
      <%= post_form.submit %>
    </div>
  </div>
<% end %>
Post Content: <div class="user-post"></div>

app/views/posts/_post.html.erb
<div class="post-content">
  <p><b><%= post.content.capitalize %></b></p>
  <p class="img"><%= image_tag post.image if post.image.present? %></p>
  <p>
    Privacy: <%= post.privacy_type %>
    <small><em><%= post.timestamp %></em></small>
  </p>  
  <p>
    <% if current_user.id == post.user_id %>
      <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'delete_post' %>
      <%= link_to 'Edit', edit_post_path(post), remote: true %>
    <% end %>
  </p>
  <p>
    <% bookmarked_post = current_user.bookmarks.find_by(post_id: post.id) %>
    <% if bookmarked_post.present? %>
      <%= link_to "remove", bookmark_path(bookmarked_post.id), :method => :delete, remote: true %>
    <% else %>
      <%= link_to "save", bookmark_index_path(:post_id => post.id), :method => :post, remote: true %>
    <% end %>
  </p>
</div>

app/views/posts/create.js.erb
$('#post-form').slideUp(350);

app/views/posts/destroy.js.erb
$('.delete_post').bind('ajax:success', function() {  
  $(this).closest('tr').fadeOut();
});

app/views/posts/edit.js.erb
$('#post-form').html("<%= j (render 'posts/form') %>");
$('#post-form').slideDown(350);

app/views/posts/index.html.erb
<div class="container">
  <div class="col-md-12 text-center">
    <h3>Welcome <%= current_user.firstname.capitalize %></h3>
  </div>

  <div class="col-md-12">
    <div class="col-md-6">
      <%= link_to new_post_path, remote: true do %>
      <button class="btn btn-primary">New Post</button>
      <% end %>
      <div id="post-form" style="display:none;"></div>
    </div>

    <div class="col-md-6">
      <div id="my-posts">
        <%= render @posts %>
      </div>
      <div id="infinite-scrolling">
        <%= will_paginate @posts %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.js.erb
$('#my-posts').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
   $(window).off('scroll');
   $('.pagination').remove();
<% end %>

app/views/posts/new.js.erb
$('#post-form').html("<%= j (render 'form') %>");
$('#post-form').slideDown(350);

app/views/posts/update.js.erb
$('#post-form').slideUp(350);