config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :posts 
  resources :bookmark,only: [:index,:create,:destroy]
  resources :profile, only: [:show] 
  resources :friendships  do
    post 'fb_friends', :on => :collection
  end
  resources :users do
    get 'search', on: :collection
  end
  match "/facebook_profile" => "facebook#facebook_profile",via: [:get, :post]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
	belongs_to :user
  belongs_to :post
  validates :user_id, presence: { message: "must be given" }
  validates :post_id, presence: { message: "should be select to bookmarked" }
  self.per_page = 20
end

app/models/device.rb
class Device < ApplicationRecord
	scope :android, -> { where(device_type: 'android') }
end

app/models/facebook_oauth_setting.rb
class FacebookOauthSetting < ApplicationRecord
	belongs_to :user
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
  belongs_to :friend, :class_name => "User",:foreign_key => 'friend_id'

  enum status: {"pending": "pending", "accepted": "accepted", "rejected": "rejected"}
end

app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :imageable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord 
  belongs_to :user
  delegate :test_user, :test_user2, to: :user
  delegate :sum, to: :CONSTANT_ARRAY
  has_many :pictures, as: :imageable
  has_many :bookmarks, dependent: :destroy
  validate :content_or_image	
  enum privacy_type: {"All": "public", "friends": "friends", "me": "me"}
  mount_uploader :image, ImageUploader
  self.per_page = 10

  scope :user_all_friends_post, lambda { |user| 
    where(:user_id => user.all_friends) }
  scope :friends_posts, -> { where(posts: {privacy_type: "friends" }) }
  scope :all_posts, -> { where(posts: {privacy_type: "public" }) }

  def content_or_image
    unless !content.blank? or !image.blank? 
      errors.add(:base, "Specify a content or a image, not both")
    end
  end

  def timestamp
    created_at.try(:strftime,'%d %B %Y %H:%M:%S')
  end
end

app/models/social_provider.rb
class SocialProvider < ApplicationRecord
end

app/models/user.rb
Person = Struct.new(:name, :address)

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  CONSTANT_ARRAY = [0,1,2,3]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable,:omniauthable, :omniauth_providers => [:facebook,:twitter,:google_oauth2]
  delegate :test_user3, to: :class
  has_many :posts,dependent: :destroy
  has_one :picture, as: :imageable
  
  has_many :bookmarks#, through: :posts
  has_many :bookmarked_posts, through: :bookmarks, source: :post
  
  mount_uploader :image, ImageUploader
  has_many :friendships

  has_many :pending_friends, -> {where(friendships: {status: "pending"})},
            :through => :friendships,
            :source => :friend
  
  has_many :friends, -> { where(friendships: {status: "accepted"}) }, 
            through: :friendships

  has_many :rejected_friends, -> {where(friendships: {status: "rejected"})},
            :through => :friendships,
            :source => :friend
                
  has_many :pending_friends, -> {where(friendships: {status: "pending"})},
            :through => :friendships,
            :source => :friend

  has_many :inverse_friendships, :class_name => "Friendship",
           :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  
  has_one :facebook_oauth_setting

  serialize :language

  ALLOWED_LANGUAGES = ["Hindi", "English", "Other"]
  
  def test_user
    "in model user method first"
  end

  def test_user2
    "in model user method second"
  end

  def self.test_user3
    "test user 3"
  end

  def self.search_user(search)
    if search.present?
      @user = User.find_by(email: search)
    end
  end

  def is_mutual_friend_with?(user)
    friendships.exists?(friend_id: user.id) || inverse_friendships.exists?(user_id: user.id)
  end 

  def get_mutual_friendship_with(user)
    mutual_friendship = friendships.where(friend_id: user.id).first
    mutual_friendship ||= inverse_friendships.where(user_id: user.id).first
    mutual_friendship
  end

  def all_friends
    friends + inverse_friends
  end

  def self.from_omniauth(auth)
    data = auth.info
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.password = Devise.friendly_token[0,20]
      user.firstname = auth.info.name  
      user.image = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        if auth.info.try(:email)
          user.email = auth.info.email
          user.save
        else
          user.email = auth.uid.to_s+"@facebook.com"
          user.save
        end
      user.skip_confirmation!
    end
  end

  def self.for_twitter_omniauth(auth)
    data = auth.info
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.emails = auth.uid.to_s+"@twitter.com"
      user.password = Devise.friendly_token[0,20]
      user.firstname = auth.info.nickname   
      user.image = auth.info.image 
      user.skip_confirmation!
    end
  end
end
      

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  respond_to :html, :js, :json

  def new
    @post = Post.new
  end

  def index
    # f_posts = Post.user_all_friends_post(current_user) 
    # all_posts = f_posts.friends_posts + current_user.posts + Post.all.all_posts
    # @posts = all_posts.sort_by(&:updated_at).paginate(page: params[:page],per_page: 3)
    # respond_to do |format|
    #   format.html
    #   format.js
    # end
    @posts = Post.paginate(page: params[:page], per_page: 15).order('created_at ASC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = t('post.create')
    else
      flash[:notice] =  t('post.create_error')
    end
    redirection_path
  end

  def destroy
    @post.destroy
    redirection_path
  end

  def update
    @post.update_attributes(post_params)
    redirection_path
  end

  private
    def redirection_path
      redirect_to posts_path
    end

    def post_params
      params.require(:post).permit(:content, :image,:privacy_type)
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  
  def show
		@user = User.find(params[:id])
		@posts = current_user.posts
	end

private
	def profile_params
	 	params.require(:user).permit(:firstname, :lastname,:email,:birth_date,:country,:language,:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    @search_user = User.order(:email).search_user(params[:search])
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/facebook_helper.rb
module FacebookHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <p class="navbar-brand">
        <%= link_to('FeedBook', '/') %>
      </p>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">  
          <li>
            <%= link_to('Posts', posts_path) %>
          </li>
         
          <li>
            <%= link_to('Profile', profile_path(current_user.id)) %>
          </li>
          
          <li><%= link_to('Bookmarks',bookmark_index_path)%></li>

          <li><%= link_to('All friends', friendships_path ) %></li>
        </ul>
      <% end %>

      <ul class="nav navbar-nav navbar-right">      
        <% if user_signed_in? %>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to('Log in', new_session_path(User)) %></li>
          <li><%= link_to('Sign Up', new_registration_path(User)) %></li>
          <li><%#= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
          <%- if devise_mapping.omniauthable? %>
            <%- resource_class.omniauth_providers.each do |provider| %>
             <li><%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %></li>
          <% end -%>
          <% end -%>
        <% end %>
      </ul>
    </div>
  </div>
 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feedbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="main">
    <%= bootstrap_flash %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>